name: Create new github release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: '${{ steps.git.outputs.version }}'
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{secrets.SSH_PRIVATE}}
    - run: git config --global user.email "tvpozytyw@gmail.com"
    - run: git config --global user.name "github-action"
    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Prepare release
      run: make prepare-release
    - run: |
        echo "commit_sha=$(git rev-parse --verify HEAD)" >> $GITHUB_OUTPUT
        echo "version=$(make next-version)" >> $GITHUB_OUTPUT
      id: git
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ steps.git.outputs.version }}',
            sha: '${{ steps.git.outputs.commit_sha }}'
          })
    - name: Release pushed tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.inputs.version }}
      run: |
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${tag}" \
            --generate-notes
    - name: After release
      env:
        tag: ${{ github.event.inputs.version }}
      run: make after-release

  build-linux:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ needs.create-release.outputs.version }}
    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Build release
      run: make build
    - name: Add executables to releae
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ needs.create-release.outputs.version }}
      run: |
        gh release upload "$tag" ngw \
            --repo="$GITHUB_REPOSITORY"

  build-windows:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ needs.create-release.outputs.version }}
    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Build release
      env:
        GOOS: windows
        GOARCH: amd64
      run: make build
    - name: Add executables to releae
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ needs.create-release.outputs.version }}
      run: |
        ls
        gh release upload "$tag" ngw.exe \
            --repo="$GITHUB_REPOSITORY"

